max-uses-per-day: 50

messages:
  enabled: §aAuto tree chopping enabled.
  disabled: §cAuto tree chopping disabled.
  no-permission: §cYou don't have permission to use this command.
  hitmaxusage: §cYou've reached the daily usage limit.