# AutoTreeChop by Maoyue
# Discord support server: https://discord.gg/uQ4UXANnP2
# Spigot Page: https://www.spigotmc.org/resources/113071

# The number of times non-VIP players can chop down trees per day,
# you can give everyone "autotreechop.vip" permission to disable it.
max-uses-per-day: 50
# Tree blocks that non-VIP players can chop down every day,
# you can give everyone "autotreechop.vip" permission to disable it.
max-blocks-per-day: 500

# Plugin message
messages:
  enabled: §aAuto tree chopping enabled.
  disabled: §cAuto tree chopping disabled.
  no-permission: §cYou don't have permission to use this command.
  hitmaxusage: §cYou've reached the daily usage limit.
  hitmaxblock: §cYou have reached your daily block breaking limit.