name: AutoTreeChop
version: '${version}'
main: org.milkteamc.autotreechop.AutoTreeChop
api-version: 1.17
author: Maoyue
description: A auto tree chopping plugin for milkteamc
softdepend: [PlaceholderAPI, CoreProtect, Residence, Lands]
folia-supported: true

libraries:
  - net.kyori:adventure-api:4.14.0
  - net.kyori:adventure-platform-bukkit:4.3.1
  - net.kyori:adventure-text-minimessage:4.14.0
  - net.kyori:adventure-text-serializer-legacy:4.14.0
  - net.kyori:adventure-text-serializer-gson:4.14.0
  - net.kyori:adventure-text-serializer-plain:4.14.0

commands:
  autotreechop:
    description: Toggle auto tree chop.
    usage: /autotreechop
    permission: autotreechop.use

  atc:
    description: Toggle auto tree chop.
    usage: /atc
    permission: autotreechop.use

permissions:
  autotreechop.use:
    description: Allows players to use the auto tree chop command.
    default: true
  autotreechop.vip:
    description: VIP permission can ignore all limit.
    default: op
  autotreechop.updatechecker:
    description: Send Update notify to player.
    default: op
  autotreechop.other:
    description: Allows players to switch other's AutoTreeChop status.
    default: op